### PR TITLE
Add support for X-Language header

### LINKED ISSUE #50: Querying content of a certain language code
using the x-language header does not work nor can i set the language in the php `kql()` helper as far as i can tell.
https://getkirby.com/docs/guide/api/introduction#language

the forum suggests it might have worked before. maybe in v1?
https://forum.getkirby.com/t/kql-querying-pages-for-all-languages/20272

### PR DESCRIPTION
**Pull request by bnomei**
closes #50

### CODE REVIEW

**Comment by lukasbestle** [comment]
Hm, it's weird that this doesn't already work. The `Cms\Api` class already does the same thing before running the router:

https://github.com/getkirby/kirby/blob/ee2669e6dd091399fd7981381e1bd8cbd94d90a6/src/Cms/Api.php#L38

I think this should also be respected for plugin API routes like the KQL query route.

**Comment by bastianallgeier** [comment]
@lukasbestle I agree. This seems more like an issue in our router.

**Comment by alancwoo** [comment]
I was trying to figure this out too and it seemed to work with the `x-language` header on Kirby `4.1.0` and kql `2.1.0`. Was this fixed somewhere in Kirby itself? https://github.com/getkirby/kirby/blame/c1e6ff77b056774543f201035f5dab6a02bfdb3b/src/Cms/Api.php#L137

(👋🏽 @bnomei )

**Comment by bastianallgeier** [comment]
@alancwoo it looks like @distantnative took care of it :)

**Comment by alancwoo** [comment]
@bastianallgeier great that does look like the case - is it possible to mention this in the docs somewhere? Looking at the [kql docs](https://github.com/getkirby/kql#query) it seems to insinuate that `languages` is a query parameter - and if I'm not mistaken, the `x-language` header is the only way to fetch a particular language, correct?

**Comment by marco-land** [comment]
I am also wondering if there is a way to fetch all translations (e.g. a page title of a certain page) in one fetch, or if I need to do a fetch it for every language?

**Pull request closed without merging**
