### PR TITLE
Support Kirby v4

### LINKED ISSUE #49: Kirby 4 compatibility
I tried KQL with Kirby 4 (alpha 5), but the output is always an error: `Access to the class \"Kirby\Content\Field\" is not supported`.
The same queries work as expected on Kirby 3.9.5.

—

Example of POST request:

```json
{
  "query": "page('home')",
  "select": {
    "title": "page.title"
  }
}
```

[❌](https://emojipedia.org/cross-mark/) Response:
```json
{
  "status":"error",
  "message":"Access to the class \"Kirby\\Content\\Field\" is not supported",
  "code":403,
  "exception":"Kirby\\Exception\\PermissionException",
  "key":"error.permission",
  "file":"Interceptor.php",
  "line":269,
  "details":[],
  "route":"query"
}
```

(Thanks so much for this essential plugin)

### PR DESCRIPTION
**Pull request by johannschopplich**
- Closes #49

This PR 1️⃣ renames the Content and Field class aliases:
- `Kirby\Cms\Field` class to `Kirby\Content\Field`
- `Kirby\Cms\Content` class to `Kirby\Content\Content`

While 2️⃣ adding an interceptor alias to keep support for Kirby 3.

### CODE REVIEW

**Comment by lukasbestle** [comment]
Thanks for your PR:

I think we could create an alias class for the old `Cms` class names. This way we will be able to keep compatibility with v3.

So something like:

```php
<?php

namespace Kirby\Kql\Interceptors\Cms;

use Kirby\Kql\Interceptors\Content\Content as NewContent;

class Content extends NewContent
{
}
```

**Comment by johannschopplich** [comment]
Thanks for the hint! To add backwards compatibility to my Kirby 3 projects, I currently rely on a similar class alias for my libraries, which basically only require one change for Kirby 4 compatibility:

```php
// Add backwards compatibility for Kirby 3
if (!class_exists('Kirby\Content\Field')) {
    class_alias('Kirby\Cms\Field', 'Kirby\Content\Field');
}
```

I'm not sure my PHP knowledge will be sufficient to replicate that using your approach for my PR, but I will give it a shot.

**Comment by johannschopplich** [comment]
Thanks for the ideas @lukasbestle, which I have implemented accordingly. But I'm running into a problem with Psalm that I can't seem to solve. Perhaps the solution is obvious to you.

**Comment by lukasbestle** [comment]
Hm, good point. Maybe a class alias could actually work as well:

```php
use Kirby\Kql\Interceptors\Content\Content;
use Kirby\Kql\Interceptors\Content\Field;

class_alias(Content::class, 'Kirby\Kql\Interceptors\Cms\Content');
class_alias(Field::class, 'Kirby\Kql\Interceptors\Cms\Field');
```

**Comment by lukasbestle** [comment]
Could you please revert `composer.json` and `composer.lock` to the currently released state? I think it would be good to keep the version requirements unchanged unless we need to.

**Comment by johannschopplich** [comment]
For sure! Done.

**Review by lukasbestle — APPROVED** [review]
Thank you very much for your work. 💛

Code-wise it looks good to me. Waiting for a second review from Bastian or Nico to confirm that this is the correct solution. Also it still needs real-world testing.

**Comment by johannschopplich** [comment]
Great! Regarding real-live testing, I'm using my fork (on which this PR is based on) for both K3 in production and a K4 test site. I can verify it works.

This is my setup (relevant lines extracted):

```json
{
  "require": {
    "getkirby/cms": "^3.9",
    "getkirby/kql": "dev-v4-compat"
  },
  "repositories": [
    {
      "url": "https://github.com/johannschopplich/kql-fork.git",
      "type": "git"
    }
  ]
}
```

**Review by bastianallgeier — APPROVED** [review]
I'm very happy with this. Thanks for the PR!

**Pull request merged**
